baseURL = "https://joshcarp.com/sysl-presentation"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true